### ISSUE TITLE
Add tooltips to explain diagrams 

### ISSUE THREAD

**Issue by h11r** [jotaen/run-monitor#1]
On the first visit on the page it was not clear for me what the different diagrams mean. Reading the blogpost gives inside but is a little much for a quick overview. A solution would be to add tooltips to the diagrams that show a title and a one sentence description.

**Comment by jotaen** [comment]
Nice and cheap idea, thanks for pointing it out.

Doesn’t do it on mobile though, but doesn’t make anything worse either. (Pareto improvement)
